baseURL = "https://www.feixiang.name/"
languageCode = "zh-CN"
title = "FX思惑"
theme = "ananke-mod"
disqusShortname = "friskfly"
[params]
  description = "FX的所见所闻，所惑所思"
  twitter = "https://twitter.com/friskfly"
  github = "https://github.com/friskfly"
  instagram = "https://www.instagram.com/friskfly/"

[Permalinks]
  post = "/:slug/"
  page = "/:slug"